### ISSUE TITLE
Error rendering data template: Result is not a Dictionary

### ISSUE THREAD

**Issue by johannwilken** [TheFes/HA-configuration#1]
Good day,

I would like to use your script and would love to get it to work:

I have changed media players to my entities. When trying to run the script
I'm getting error: Error rendering data template: Result is not a Dictionary

Here are the full error:

Logger: homeassistant.components.websocket_api.http.connection
Source: helpers/service.py:238
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 10:28:05 AM (4 occurrences)
Last logged: 10:29:30 AM

[140159867333552] Error rendering data template: Result is not a Dictionary
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1495, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1530, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 273, in service_handler
    await script_entity.async_turn_on(
  File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 377, in async_turn_on
    await coro
  File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 403, in _async_run
    return await self.script.async_run(script_vars, context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1260, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 363, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 381, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 557, in _async_call_service_step
    params = service.async_prepare_call_from_config(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 238, in async_prepare_call_from_config
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Error rendering data template: Result is not a Dictionary

Can you please point out to what I am doing wrong?

Thank you

**Comment by johannwilken** [comment]
Here are another error in the logs:

Logger: homeassistant.helpers.template
Source: helpers/template.py:1779
First occurred: 10:28:05 AM (8 occurrences)
Last logged: 10:29:30 AM

Template variable warning: 'tts_target' is undefined when rendering '{% if voice_tts_target is defined %} {{ [ voice_tts_target ] }} {% else %} {% set tts_list = tts_target.replace(' ' , '').split(',') if tts_target is string else tts_target %} {% set speaker_group_list = speaker_groups.keys() | list if speaker_groups is defined else [] %} {% set tts_target_group = tts_list | select('in', speaker_group_list) | list %} {% set tts_target_single = tts_list | reject('in', speaker_group_list) | list %} {% set ns = namespace(single = []) %} {% for group in tts_target_group %} {% set ns.single = ns.single + speaker_groups[group] %} {% endfor %} {% set tts_group_entities = ns.single | unique | list %} {% set single_not_in_group = tts_target_single | reject('in', tts_group_entities) | list %} {% if speaker_group_split | default(default_group_split | default(False)) %} {{ tts_group_entities + single_not_in_group }} {% else %} {{ tts_target_group + single_not_in_group }} {% endif %} {% endif %}'

**Comment by TheFes** [comment]
Do you try to run the script from configuration > scripts? It doesn't work like that, you need to provide information, like to which device it should be sent, and which message should be sent.

You should call this script from another script or automation, or from your dashboard, providing this data.

Have a look at the detailed description and prerequisites here: https://community.home-assistant.io/t/script-to-resume-radio-tunein-and-spotify-after-tts-on-google-home-speakers/326634

The first issue could also be related to that.

**Comment by johannwilken** [comment]
Sorry, My bad. All working, I only had to change the tts service to tts.google_translate_say.

Thanks man, this is awesome, thanks for putting in the time to write this script. I have been looking for something 
like this for I don't know how long.

And thanks for the quick reply aswell.

Hope you have a great festive season and a great 2022.

**Comment by TheFes** [comment]
Good to hear, happy holidays for you as well!
