### ISSUE TITLE
transition_lights.yaml

### ISSUE THREAD

**Issue by deadlypantsd** [TheFes/HA-configuration#103]
1 type-o, "fasle" -> false line 210
changed "abs * 1.5" to "abs * 30" lines 345,353,372-374, 418,426,445-447

30 could *probably* be lower, but it seems to work

**Comment by deadlypantsd** [comment]
Check this as well:

Check if transition for this light is not already active: Error executing script. Error rendering template for variables at pos 4: TypeError: '>' not supported between instances of 'str' and 'int'  -- looking into it to see if I can spot it

Full Errot:
```
2023-10-19 16:55:30.864 ERROR (MainThread) [homeassistant.components.script.transition_lights_perform_transition] 00 - Perform transition light brightness, color temperature and/or RGB values (helper script): Check if transition for this light is not already active: Error executing script. Error rendering template for variables at pos 4: TypeError: '>' not supported between instances of 'str' and 'int'
2023-10-19 16:55:30.865 ERROR (MainThread) [homeassistant.components.script.transition_lights_perform_transition] 00 - Perform transition light brightness, color temperature and/or RGB values (helper script): Error executing script. Error rendering template for if at pos 2: TypeError: '>' not supported between instances of 'str' and 'int'
2023-10-19 16:55:30.868 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 568, in async_render
    render_result = _render_with_context(self.template, compiled, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2198, in _render_with_context
    return template.render(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "
  File "/usr/local/lib/python3.11/site-packages/jinja2/filters.py", line 502, in do_max
    return _min_or_max(environment, value, max, case_sensitive, attribute)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jinja2/filters.py", line 462, in _min_or_max
    return func(chain([first], it), key=key_func)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '>' not supported between instances of 'str' and 'int'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/script/__init__.py", line 597, in _async_run
    return await self.script.async_run(script_vars, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1579, in async_run
    return await asyncio.shield(run.async_run())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 420, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 470, in _async_step
    self._handle_exception(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 493, in _handle_exception
    raise exception
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 468, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 951, in _async_if_step
    await self._async_run_script(if_data["if_then"])
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1069, in _async_run_script
    await self._async_run_long_action(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 666, in _async_run_long_action
    return long_task.result()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1579, in async_run
    return await asyncio.shield(run.async_run())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 420, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 470, in _async_step
    self._handle_exception(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 493, in _handle_exception
    raise exception
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 468, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1021, in _async_variables_step
    self._variables = self._action[CONF_VARIABLES].async_render(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script_variables.py", line 62, in async_render
    rendered_variables[key] = template.render_complex(
                              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 239, in render_complex
    return value.async_render(variables, limited=limited, parse_result=parse_result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 570, in async_render
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: TypeError: '>' not supported between instances of 'str' and 'int'
```

**Comment by TheFes** [comment]
I'm thinking of changing that check to a check on context, but I need some time to work on that.
Can you check in the script trace in which step that error occurs?

**Comment by deadlypantsd** [comment]
I'll have to remember how I sparked this. I think it was when changing both temp and brightness at the same time.

**Comment by TheFes** [comment]
were you using the GUI to set the settings for the script? If so, I think it should be fixed now.
The issue was that the GUI would set things like `br_start: Current setting`  which wasn't expected.
I now convert those to `none` when calling the script which performs the transition.

I also changed all `1.5`s to `5`, hope that will be enough, and I fixed the typo in `false`

**Comment by TheFes** [comment]
The check on `context` doesn't seem to be possible as I intended

**Comment by TheFes** [comment]
Closed this issue for now, if new things come up, please let me know.
